### ISSUE TITLE
InvalidArgumentException: The JWT string must have two dots

### ISSUE THREAD

**Issue by dri94** [kreait/firebase-php#107]
I keep getting this exception below. I have researched it and the only solution people say is that they were copying their json wrong. However i printed my json out to console right before it is passed to ServiceAccount::fromJSON() and it is correct. What else could be the problem?

 InvalidArgumentException: The JWT string must have two dots in /app/vendor/lcobucci/jwt/src/Parser.php:89
2017-07-26T16:05:28.687712+00:00 app[web.1]: Stack trace:
2017-07-26T16:05:28.687991+00:00 app[web.1]: #0 /app/vendor/lcobucci/jwt/src/Parser.php(59): Lcobucci\JWT\Parser->splitJwt(NULL)
2017-07-26T16:05:28.688217+00:00 app[web.1]: #1 /app/vendor/kreait/firebase-tokens/src/Verifier.php(42): Lcobucci\JWT\Parser->parse(NULL)

**Comment by jeromegamez** [comment]
The error hints to an issue not with your service account JSON but to an issue with ID token verification, so I guess the problem occurs somewhere else in your code.

**Comment by dri94** [comment]
removed my verification code and seen this is the case. Thank you. Closing issue
