### ISSUE TITLE
Invalid Issuer

### ISSUE THREAD

**Issue by dri94** [kreait/firebase-php#111]
#### 1. Which version of `kreait/firebase-php` are you using?
3.1.2

#### 2. Which version of PHP are you using?
7

#### 3. What's the issue?

When trying to verify the user with Authentication i get 'this token has an invalid issuer'. Where and how do i fix this?

#### 4. Code that lead to the issue
My code:
```

$id = $data['auth'];
$tokenHandler = $app->firebase->getTokenHandler();
$customToken = $tokenHandler->createCustomToken($id);
$idToken = $tokenHandler->verifyIdToken($customToken);
```

```
Aug 19 15:24:55 revel-dev app/web.1: [19-Aug-2017 22:24:54 UTC] Firebase\Auth\Token\Exception\InvalidToken: This token has an invalid issuer. in /app/vendor/kreait/firebase-tokens/src/Verifier.php:82 
Aug 19 15:24:55 revel-dev app/web.1: Stack trace: 
Aug 19 15:24:55 revel-dev app/web.1: #0 /app/vendor/kreait/firebase-tokens/src/Verifier.php(47): Firebase\Auth\Token\Verifier->verifyIssuer(Object(Lcobucci\JWT\Token)) 
Aug 19 15:24:55 revel-dev app/web.1: #1 /app/vendor/kreait/firebase-tokens/src/Handler.php(33): Firebase\Auth\Token\Verifier->verifyIdToken(Object(Lcobucci\JWT\Token)) 
Aug 19 15:24:55 revel-dev app/web.1: #2 /app/web/index.php(303): Firebase\Auth\Token\Handler->verifyIdToken(Object(Lcobucci\JWT\Token)) 
Aug 19 15:24:55 revel-dev app/web.1: [19-Aug-2017 22:24:54 UTC] Firebase\Auth\Token\Exception\InvalidToken: This token has an invalid issuer. in /app/vendor/kreait/firebase-tokens/src/Verifier.php:82 
Aug 19 15:24:55 revel-dev app/web.1: Stack trace: 
Aug 19 15:24:55 revel-dev app/web.1: #0 /app/vendor/kreait/firebase-tokens/src/Verifier.php(47): Firebase\Auth\Token\Verifier->verifyIssuer(Object(Lcobucci\JWT\Token)) 
Aug 19 15:24:55 revel-dev app/web.1: #1 /app/vendor/kreait/firebase-tokens/src/Handler.php(33): Firebase\Auth\Token\Verifier->verifyIdToken(Object(Lcobucci\JWT\Token)) 
Aug 19 15:24:55 revel-dev app/web.1: #2 /app/web/index.php(303): Firebase\Auth\Token\Handler->verifyIdToken(Object(Lcobucci\JWT\Token)) 

```

**Comment by jeromegamez** [comment]
The `verifyIdToken` method expects an ID token and will not work with custom tokens.

It is meant to be used to verify ID tokens that you receive from another party like a Firebase JS application where you would get an ID token with `firebase.auth().currentUser.getToken()` which you can pass to the backend and verify that it is indeed valid by using the `verifyIdToken` method.

You can find more information here: https://firebase.google.com/docs/auth/admin/verify-id-tokens#retrieve_id_tokens_on_clients

**Comment by dri94** [comment]
Thanks for the information
