### ISSUE TITLE
Uncaught 503 exception when Google OAuth is down

### ISSUE THREAD

**Issue by x1nixmzeng** [kreait/firebase-php#131]
#### 1. Which version of `kreait/firebase-php` are you using?

2.3.1

#### 2. Which version of PHP are you using?

7.0.16

#### 3. What's the issue?

In the rare cases when the Google OAuth service is down I believe the APIException class should handle this error.

```
 PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `503 Service Unavailable` response:
 {
  "error": "internal_failure",
  "error_description": "Backend Error"
 }
```

Looking at the list of handled Fig status this should be possible by adding a check for this value:

```const STATUS_SERVICE_UNAVAILABLE = 503;```

As even on master this does not appear to be handled: https://github.com/kreait/firebase-php/blob/672c2708c851c14340f37422390c48edf85f0d54/src/Firebase/Exception/ApiException.php#L38

#### 4. Code that lead to the issue

This is just an unhandled exception in `APIException.php`. My version of the library was outdated, but the latest code still should support 503 errors.

**Comment by jeromegamez** [comment]
Hey @x1nixmzeng! Thank you for taking the time to report this issue, you are right, the library should handle server errors! I will add support for that in the upcoming release!

**Comment by jeromegamez** [comment]
@x1nixmzeng I believe this is not handled by an ApiException, but by the AuthException, but I am not sure. Can you please attach a full stack trace of the error, or a code example that led to the error? Looking at the code, any errors should be handled by `ApiException` or `AuthException`, but I can't test this at the moment.

**Comment by x1nixmzeng** [comment]
Hello, sorry for the delay - is is the stack trace from the logs:

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `503 Service Unavailable` response:
{
 "error": "internal_failure",
 "error_description": "Backend Error"
}

Stack trace:
 in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
#0 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /app/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /app/vendor/guzzlehttp/promises/src/Promi in /app/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php on line 28
```

**Comment by x1nixmzeng** [comment]
I also have another error in my logs which points to the server response returning HTML rather than JSON.

```
PHP Fatal error:  Uncaught Firebase\Exception\InvalidArgumentException: json_decode error: Syntax error in /app/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php:55
Stack trace:
#0 /app/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php(21): Firebase\Util\JSON::decode('<!DOCTYPE html>...', true)
#1 /app/vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php(78): Firebase\Exception\ApiException::wrapThrowable(Object(GuzzleHttp\Exception\ServerException))
#2 /app/vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php(70): Firebase\Database\ApiClient->request('PATCH', Object(GuzzleHttp\Psr7\Uri), Array)
#3 /app/vendor/kreait/firebase-php/src/Firebase/Database/Reference.php(389): Firebase\Database\ApiClient->update(Object(GuzzleHttp\Psr7\Uri), Array)
#4 /app/[redacted].php(569): Firebase\Database\Reference->update(Array)
#5 /app/[redacted].php(108): [redacted]->[method](Array)
#6 {main}
  thrown in /app/vendor/kreait/firebase-php/src/Firebase/Util/JSON.php on line 55
```

**Comment by jeromegamez** [comment]
@x1nixmzeng When you update to Release 3.5.0 (out now \o/), could you please try again and see if things get better? The library should now be able to handle non-JSON responses better.

**Comment by jeromegamez** [comment]
Closing this now, but feel free to add further comments or to open a new issue if the problem persists.

**Comment by x1nixmzeng** [comment]
I'm am still getting sparodic errors on 3.5.0 with Firebase, but the JSON response errors are gone.

Here are the callstacks. At the moment I am adding further logging to my app to see if I can catch the issue.

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ServerException: Server error: `POST https://www.googleapis.com/oauth2/v4/token` resulted in a `503 Service Unavailable` response:
{
 "error": "internal_failure",
"error_description": "Backend Error"
}

in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /app/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#2 /app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#5 /app/vendor/guzzlehttp/promises/src/Promi in /app/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php on line 50
```

And

```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#3 /app/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#0 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#4 /app/vendor/guzzlehttp/guzzle/src/Handler/Pr in /app/vendor/kreait/firebase-php/src/Firebase/Exception/ApiException.php on line 50
```

**Comment by onim4ru** [comment]
Did you get some changes about this error ? 

I have the same one right now without clue to fix it
