### ISSUE TITLE
How to correctly handle device tokens no longer existing?

### ISSUE THREAD

**Issue by jamesliscombe** [kreait/firebase-php#275]
Hello,

I'm currently using the SDK and getting results as expected, with notifications reaching specific Android devices.

I've tested both deleting the app and entering an old device token. 

Each time I get the following error:

`Fatal error: Uncaught Kreait\Firebase\Exception\Messaging\NotFound: Client error: `POST https://fcm.googleapis.com/v1/projects/a-327f9/messages:send` resulted in a `404 Not Found` response: { "error": { "code": 404, "message": "Requested entity was not found.", "status": "NOT_FOUND", "detail (truncated...) in /home/appsuknow01/client/prototype/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php:76 Stack trace: #0 /home/appsuknow01/client/prototype/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php(51): Kreait\Firebase\Exception\MessagingException->withResponse(Object(GuzzleHttp\Psr7\Response)) #1 /home/appsuknow01/client/prototype/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(52): Kreait\Firebase\Exception\MessagingException::fromRequestException(Object(GuzzleHttp\Exception\ClientException)) #2 /home/appsuknow01/client/prototype/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(26): Kreait\Firebase\Messaging\ApiClient->request('P in /home/appsuknow01/client/prototype/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php on line 76`

I can't find any section on exception handling in the docs, so unsure how to correctly handle these types of errors.

**Comment by jamesliscombe** [comment]
Looks like 'Exception' has started catching this. No idea why this didn't work last night; nothing has changed but as of this morning the generic Exception catches this.

        try {
            $messaging = $firebase->getMessaging();
            $messaging->send($message);

            $_SESSION['message_sess'] = "Push notification sent";
        } catch (Exception $e) {
            $_SESSION['message_sess'] = "Unable to send notification, customer has likely disabled push notifications from this app.";
            
        } finally {
            $URL="GoSomewhere.com";
            echo "<script type='text/javascript'>document.location.href='{$URL}';</script>";
            echo '<META HTTP-EQUIV="refresh" content="0;URL=' . $URL . '">';
        }
