### ISSUE TITLE
Request is missing required authentication credential. Expected OAuth 2

### ISSUE THREAD

**Issue by natezeevo** [kreait/firebase-php#277]
Please avoid using the issue tracker for questions or help. Submitting issues to this repository are usually reserved for bugs, feature requests, or changes to the source code. We have a help channel at https://gitter.im/kreait/firebase-php (you can sign in with your GitHub account). If nobody can answer your question, tag @jeromegamez in your question.

Also see past issues and https://firebase-php.readthedocs.io/en/latest/troubleshooting.html to check if your problem has already been covered.

Please chose a descriptive title for your issue and delete everything before and including this line before submitting the issue.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added). 

When attempting to post a cloud message to firebase to send to a device, the process crashes (now fixed to be in a try-catch block to stop this)

## Environment

- PHP Version (`php -v`): PHP 7.2.12-1
- Firebase PHP SDK version (`composer show | grep kreait`):
kreait/firebase-php                   4.18.0             Firebase Admin SDK
kreait/firebase-tokens                1.7.2              A library to work with Firebase tokens
kreait/gcp-metadata                   1.0.1              Get the metadata from a Google Cloud Platform environment.

## Details

If necessary, describe the problem you have been experiencing in more detail.

Laravel error log (app name changed for security)

```
prod.ERROR: Client error: `POST https://fcm.googleapis.com/v1/projects/my-app-aaa11/messages:send` resulted in a `401 Unauthorized` response:
{
  "error": {
    "code": 401,
    "message": "Request is missing required authentication credential. Expected OAuth 2  (truncated...)
 {"exception":"[object] (Kreait\\Firebase\\Exception\\Messaging\\AuthenticationError(code: 401): Client error: `POST https://fcm.googleapis.com/v1/projects/my-app-aaa11/messages:send` resulted in a `401 Unauthorized` response:
{
  \"error\": {
    \"code\": 401,
    \"message\": \"Request is missing required authentication credential. Expected OAuth 2  (truncated...)
 at /var/www/my-app/httpdocs/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php:76)
[stacktrace]
#0 /var/www/my-app/httpdocs/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingException.php(51): Kreait\\Firebase\\Exception\\MessagingException->withResponse(Object(GuzzleHttp\\Psr7\\Response))
#1 /var/www/my-app/httpdocs/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(52): Kreait\\Firebase\\Exception\\MessagingException::fromRequestException(Object(GuzzleHttp\\Exception\\ClientException))
#2 /var/www/my-app/httpdocs/vendor/kreait/firebase-php/src/Firebase/Messaging/ApiClient.php(26): Kreait\\Firebase\\Messaging\\ApiClient->request('POST', 'messages:send', Array)
#3 /var/www/my-app/httpdocs/vendor/kreait/firebase-php/src/Firebase/Messaging.php(53): Kreait\\Firebase\\Messaging\\ApiClient->sendMessage(Object(Kreait\\Firebase\\Messaging\\CloudMessage))
#4 /var/www/my-app/httpdocs/app/Entry.php(81): Kreait\\Firebase\\Messaging->send(Object(Kreait\\Firebase\\Messaging\\CloudMessage))
#5 /var/www/my-app/httpdocs/app/GiveawayPeriod.php(114): App\\Entry->notify()
#6 /var/www/my-app/httpdocs/app/Giveaway.php(174): App\\GiveawayPeriod->findWinners()
#7 /var/www/my-app/httpdocs/app/Console/Commands/ScheduleGiveawayFinish.php(41): App\\Giveaway::triggerFinished()
#8 [internal function]: App\\Console\\Commands\\ScheduleGiveawayFinish->handle()
#9 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#10 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#12 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#13 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\\Container\\Container->call(Array)
#14 /var/www/my-app/httpdocs/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#15 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#16 /var/www/my-app/httpdocs/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 /var/www/my-app/httpdocs/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\ScheduleGiveawayFinish), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#18 /var/www/my-app/httpdocs/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#19 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /var/www/my-app/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /var/www/my-app/httpdocs/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 {main}
"}
```

## Code to reproduce issue

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
		$deviceToken = $this->user->firebase_token;
		
		try {

			if (!empty($deviceToken)) {
				$serviceAccount = ServiceAccount::fromJson(
					'{
  "type": "service_account",
  "project_id": "my-app-aaa11",
  "private_key_id": "[removed]",
  "private_key": "-----BEGIN PRIVATE KEY----- [removed] -----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-qd6wb@my-app-aaa11.iam.gserviceaccount.com",
  "client_id": "[removed]",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-qd6wb%40my-app-aaa11.iam.gserviceaccount.com"
}');
				$firebase = (new Firebase\Factory())
					->withServiceAccount($serviceAccount)
					->create();
				$messaging = $firebase->getMessaging();

				$title = 'You Win';
				$body = 'You are a Winner!';

				$notification = Notification::fromArray([
					'title' => $title,
					'body' => $body
				]);

				$message = CloudMessage::withTarget('token', $deviceToken)
					->withNotification($notification);

				$messaging->send($message);
			}
		} catch (\Exception $e) {
			$exceptionHandler = new Handler();
			$exceptionHandler->report($e);
		}
```

**Comment by jeromegamez** [comment]
On first look, I don't see an issue with the code itself... please try this:

```php
try {
    // ...
    $messaging->send($message);
}  catch (\Kreait\Firebase\Exception\MessagingException $e) {
    dd($e->errors());
}
```

This should allow you to see the full and detailed error that the FCM API returned and help with debugging.

**Comment by natezeevo** [comment]
The error log was so helpful: Invalid APNS credential

So for some reason when creating like above it isn't getting the correct credentials for authenticating

**Comment by jeromegamez** [comment]
I don’t really know how device token registrations work, but it looks as if the authentication to the FCM API itself is working fine (you send the request and Firebase accepts it), but the token seems not to be registered with the iOS application assigned to your project, could that be?

**Comment by natezeevo** [comment]
I've just re-created and uploaded to firebase. Will find out soon

**Comment by jeromegamez** [comment]
I'm closing this issue due to inactivity and because it doesn't seem to be related to the library itself. Feel free to add further comments if needed.
