### ISSUE TITLE
404 Not Found using firebase-php 2.0-beta1

### ISSUE THREAD

**Issue by Mygod** [kreait/firebase-php#30]
```
2016-08-16T07:54:22.313212+00:00 heroku[router]: at=info method=GET path="/wogleaderboard/refresh/" host=zh.mygod.tk request_id=2b166b0e-4d23-4a17-822d-bb29313344dd fwd="210.140.195.107,108.162.226.55" dyno=web.1 connect=0ms service=330ms status=500 bytes=201
2016-08-16T07:54:22.310262+00:00 app[web.1]: [16-Aug-2016 07:54:22 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://firebase-mygod.firebaseio.com/wogleaderboard/players` resulted in a `404 Not Found` response:
2016-08-16T07:54:22.310274+00:00 app[web.1]: {
2016-08-16T07:54:22.310280+00:00 app[web.1]:   "error" : "404 Not Found
2016-08-16T07:54:22.310309+00:00 app[web.1]: 
2016-08-16T07:54:22.310292+00:00 app[web.1]: }
2016-08-16T07:54:22.310373+00:00 app[web.1]:  in /app/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
2016-08-16T07:54:22.310514+00:00 app[web.1]: #0 /app/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
2016-08-16T07:54:22.310393+00:00 app[web.1]: Stack trace:
2016-08-16T07:54:22.310597+00:00 app[web.1]: #1 /app/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
2016-08-16T07:54:22.310731+00:00 app[web.1]: #2 /app/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
2016-08-16T07:54:22.310809+00:00 app[web.1]: #3 /app/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
2016-08-16T07:54:22.311056+00:00 app[web.1]: #5 /app/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\Promise\P in /app/vendor/kreait/firebase-php/src/Firebase/Database/ApiClient.php on line 120
2016-08-16T07:54:22.310907+00:00 app[web.1]: #4 /app/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
2016-08-16T07:54:22.311272+00:00 app[web.1]: 10.137.144.23 - - [16/Aug/2016:07:54:21 +0000] "GET /wogleaderboard/refresh/ HTTP/1.1" 500 13 "https://zh.mygod.tk/wogleaderboard/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.8 Safari/537.36
```

The problem is that I'm using a project migrated from the old `firebase.com`. And probably because of the duplicate names, it got renamed to `firebase-mygod`. But the url is still `mygod.firebaseio.com` instead of `firebase-mygod.firebaseio.com`.

**Comment by jeromegamez** [comment]
The first edge case, I like it - and thanks for taking the time to give V2.0 a try. I will add an optional database URI parameter to the `Firebase` class right after this comment - in the meantime, you could do this:

```php
use Firebase\ServiceAccount;
use GuzzleHttp\Psr7\Uri;

$serviceAccount = ServiceAccount::fromValue(__DIR__.'/google-service-account.json');
$dabaseUri = new Uri('https://mygod.firebaseio.com');

$firebase = new \Firebase\V3\Firebase($serviceAccount, $dabaseUri);
```

**Comment by Mygod** [comment]
That worked. Thanks!

Btw I see that 2.0 is still using REST APIs under the hood. Is there any plan to use WebSocket or something like that? That'd be awesome!

**Comment by jeromegamez** [comment]
The change is now in: https://github.com/kreait/firebase-php/commit/08352c5a9582e0bc05ae9101ca6fd6fd103d7bd8 - thanks again for notifying me about it!

I would have liked to use Websockets from the start, but unfortunately all 3rd party SDKs have only the REST API to work with. My plan though is to make V2.0 stable and well documented and then approach the Firebase core team to ask them if it was possible to push the PHP SDK further :)

I will close this issue now, but I appreciate every other issue that you will open :). Thanks again!
