### ISSUE TITLE
The header \"kid\" is missing.

### ISSUE THREAD

**Issue by LiakosC** [kreait/firebase-php#403]
**Describe the bug**
Exception "The header \"kid\" is missing." when trying to `$auth->verifyIdToken($tokenString)`

**To Reproduce**
```php
$factory = (new Factory)
            ->withServiceAccount('/path/to/creds.json')
            ->withProjectId('project-id');
$auth = $factory->createAuth();
$tokenID = $auth->createCustomToken('user-id', [
    'premiumAccount' => true,
]);
$tokenString = (string) $tokenID;
$verifiedToken = $auth->verifyIdToken($tokenString, true);
```

**Stack Trace**
```
"name": "Exception",
    "message": "The header \"kid\" is missing.",
    "code": 0,
    "type": "Firebase\\Auth\\Token\\Exception\\InvalidToken",
    "file": "/mnt/c/users/liakos/Repos/neov-server/vendor/kreait/firebase-tokens/src/Firebase/Auth/Token/Verifier.php",
    "line": 128,
    "stack-trace": [
        "#0 /mnt/c/users/liakos/Repos/neov-server/vendor/kreait/firebase-tokens/src/Firebase/Auth/Token/Verifier.php(68): Firebase\\Auth\\Token\\Verifier->getKey(Object(Lcobucci\\JWT\\Token))",
        "#1 /mnt/c/users/liakos/Repos/neov-server/vendor/kreait/firebase-php/src/Firebase/Auth/IdTokenVerifier.php(53): Firebase\\Auth\\Token\\Verifier->verifyIdToken(Object(Lcobucci\\JWT\\Token))",
        "#2 /mnt/c/users/liakos/Repos/neov-server/vendor/kreait/firebase-php/src/Firebase/Auth.php(521): Kreait\\Firebase\\Auth\\IdTokenVerifier->verifyIdToken(Object(Lcobucci\\JWT\\Token))",
        "#3 /path/to/FirebaseController.php(34): Kreait\\Firebase\\Auth->verifyIdToken('eyJ0eXAiOiJKV1Q...', true)",
```

**Comment by jeromegamez** [comment]
The method is called `verifyIdToken`, you are trying to verify a custom token 😅

**Comment by LiakosC** [comment]
Hi @jeromegamez ,

I have modified my code as you suggested:

```
$factory = (new Factory)
            ->withServiceAccount('/path/to/creds.json')
            ->withProjectId('project-id');
$auth = $factory->createAuth();
$tokenID = 'long-token-string-coming-from-client';
$tokenString = (string) $tokenID;
$verifiedToken = $auth->verifyIdToken($tokenString, true);
```

Still I was getting an error. Now a different one: `CONFIGURATION_NOT_FOUND`.

Then I changed line:
`$verifiedToken = $auth->verifyIdToken($tokenString, true);`
to:
`$verifiedToken = $auth->verifyIdToken($tokenString);`

Now it is working perfectly. Thank you for your reply, and for your effort on this SDK.

**Comment by jeromegamez** [comment]
You're welcome and thank you for sharing your findings, this will certainly be helpful for others that stumble upon this issue! 🌺
