### ISSUE TITLE
Can't call fromJsonFile from ServiceAccount since it private method

### ISSUE THREAD

**Issue by agusadyandana** [kreait/firebase-php#408]
**Description**
I want to run this code:
```php
$serviceAccount = ServiceAccount::fromJsonFile(FCPATH .'google-services.json');
```
Which I can see on every reference. But I get this error:
```php
Fatal error: Uncaught Error: Call to private method Kreait\Firebase\ServiceAccount::fromJsonFile() from context 'Price' in C:\xampp\htdocs\bigio\priangandev\application\modules\api\controllers\price.php:19 Stack trace: #0 C:\xampp\htdocs\bigio\priangandev\application\libraries\REST_Controller.php(329): Price->firebase_get() #1 C:\xampp\htdocs\bigio\priangandev\application\libraries\REST_Controller.php(316): REST_Controller->_fire_method(Array, Array) #2 C:\xampp\htdocs\bigio\priangandev\system\core\CodeIgniter.php(325): REST_Controller->_remap('firebase', Array) #3 C:\xampp\htdocs\bigio\priangandev\index.php(202): require_once('C:\\xampp\\htdocs...') #4 {main} thrown in C:\xampp\htdocs\bigio\priangandev\application\modules\api\controllers\price.php on line 19
```
**Bonus Question**
Where I can find json file for this function?

**Environment:**
 - OS: Windows 10
 - PHP version: 7.3.5
 - Firebase SDK Version: 5.1.0
 - (Just in case) Composer.json
```json
{
    "require": {
        "kreait/firebase-php": "^5.1"
    }
}
```

**Comment by agusadyandana** [comment]
Sorry, I think I just found the solution from documentation version 5.1.0:
```php
$factory = (new Factory)->withServiceAccount('/path/to/firebase_credentials.json');
```
I just read the documentation, but most of my reference before use class ServiceAccount, that's why. LOL
