### ISSUE TITLE
Trying to send the notification for android devices

### ISSUE THREAD

**Issue by balagurubaran** [kreait/firebase-php#430]
For iOS, APNS notification is working fine while trying to send the notification to android device using the below code am getting an error

 // Example from https://firebase.google.com/docs/cloud-messaging/admin/send-messages#android_specific_fields
            $config = AndroidConfig::fromArray(['ttl' => '3600s', 'priority' => 'normal', 'notification' => ['title' => $title, 'body' => $body]]);
           
            $message = $message->withAndroidConfig($config);

error:

**Environment (please complete the following information):**
 - OS: Cpanle could be linux 
 - PHP version: PHP 5.2

 Error 

[06-Jun-2020 14:51:19 America/Chicago] PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 6: getaddrinfo() thread failed to start
 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/****/public_html/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 /home/****/public_html/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/****/public_html/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/****/public_html/composer/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/****/public_html/composer/vendor/guzz in /home/****/public_html/composer/vendor/kreait/firebase-php/src/Firebase/Exception/MessagingApiExceptionConverter.php on line 89

**Comment by balagurubaran** [comment]
Fixed iss
