### ISSUE TITLE
Bug: invalid promise rejected state processing

### ISSUE THREAD

**Issue by itkreydo** [kreait/firebase-php#535]
Description

```
Error: Call to a member function getMessage() on null in /app/vendor/kreait/firebase-php/src/Firebase/Messaging/AppInstanceApiClient.php:90
Stack trace:
#0 /app/vendor/kreait/firebase-php/src/Firebase/Messaging.php(178): Kreait\Firebase\Messaging\AppInstanceApiClient->subscribeToTopics(Array, Object(Kreait\Firebase\Messaging\RegistrationTokens))
#1 /app/vendor/kreait/firebase-php/src/Firebase/Messaging.php(159): Kreait\Firebase\Messaging->subscribeToTopics(Array, Array)
```
Bug in `subscribeToTopics()` and `unsubscribeFromTopics()` method in `Firebase/Messaging/AppInstanceApiClient.php` when one of promise was rejected.
promise with state `rejected` doesn't has a `value` property, it has a `reason` instead 

https://github.com/kreait/firebase-php/blob/dde766a4d5c08ee80fa2f336edb5b983126b8cc1/src/Firebase/Messaging/AppInstanceApiClient.php#L90

```
composer show | grep kreait
The "hirak/prestissimo" plugin (installed globally) was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
kreait/clock                          1.1.0               A PHP 7.0 compatible clock abstraction
kreait/firebase-php                   5.12.0              Firebase Admin SDK
kreait/firebase-tokens                1.13.0              A library to work with Firebase tokens
```

**Comment by jeromegamez** [comment]
Good catch, thanks! 🌺 

Merged #536 with f468d13fe5950add4a065fc2a11e9a03dba461de
