### ISSUE TITLE
Create User Now return HTTP 400 Bad Request

### ISSUE THREAD

**Issue by the-code-writer** [kreait/firebase-php#704]
### Describe the issue you are experiencing

I have been using **Firebase Auth Create User** without problems

All of a sudden its started showing Error 400 Bad Request

Please help me solve this issue. I have checked my Firebase Admin SDK key and its the correct one.

### Installed packages

```
bshaffer/oauth2-server-php         v1.10.0 OAuth2 Server for PHP
clue/stream-filter                 v1.6.0  A simple and modern approach to stre...
codeigniter4/framework             v4.1.9  The CodeIgniter framework v4
doctrine/inflector                 2.0.4   PHP Doctrine Inflector is a small li...
doctrine/instantiator              1.4.1   A small, lightweight utility to inst...
fabpot/goutte                      v4.0.2  A simple PHP Web Scraper
fig/http-message-util              1.1.5   Utility classes and constants for us...
firebase/php-jwt                   v5.5.1  A simple library to encode and decod...
google/auth                        v1.21.0 Google Auth Library for PHP
google/cloud-core                  v1.45.0 Google Cloud PHP shared dependency, ...
google/cloud-storage               v1.27.0 Cloud Storage Client for PHP
google/crc32                       v0.1.0  Various CRC32 implementations
guzzlehttp/guzzle                  7.4.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.5.1   Guzzle promises library
guzzlehttp/psr7                    2.2.1   PSR-7 message implementation that al...
hamcrest/hamcrest-php              v2.0.1  This is the PHP port of Hamcrest Mat...
illuminate/bus                     v9.14.1 The Illuminate Bus package.
illuminate/collections             v9.14.1 The Illuminate Collections package.
illuminate/conditionable           v9.14.1 The Illuminate Conditionable package.
illuminate/container               v9.14.1 The Illuminate Container package.
illuminate/contracts               v9.14.1 The Illuminate Contracts package.
illuminate/database                v9.14.1 The Illuminate Database package.
illuminate/events                  v9.14.1 The Illuminate Events package.
illuminate/macroable               v9.14.1 The Illuminate Macroable package.
illuminate/pipeline                v9.14.1 The Illuminate Pipeline package.
illuminate/support                 v9.14.1 The Illuminate Support package.
jean85/pretty-package-versions     2.0.5   A library to get pretty versions str...
jenssegers/mongodb                 v3.9.0  A MongoDB based Eloquent model and Q...
kint-php/kint                      4.1.2   Kint - debugging tool for PHP develo...
kreait/clock                       1.2     A PHP 7.0 compatible clock abstraction
kreait/firebase-php                5.26.2  Firebase Admin SDK
kreait/firebase-tokens             1.16.1  A library to work with Firebase tokens
laminas/laminas-escaper            2.10.0  Securely and safely escape HTML, HTM...
lcobucci/clock                     2.2.0   Yet another clock abstraction
lcobucci/jwt                       4.1.5   A simple library to work with JSON W...
mailgun/mailgun-php                v3.5.1  The Mailgun SDK provides methods for...
mailjet/mailjet-apiv3-php          v1.5.5  PHP wrapper for the Mailjet API
masterminds/html5                  2.7.5   An HTML5 parser and serializer.
mikey179/vfsstream                 v1.6.10 Virtual file system to mock the real...
mockery/mockery                    1.5.0   Mockery is a simple yet flexible PHP...
mongodb/mongodb                    1.12.0  MongoDB driver library
monolog/monolog                    2.6.0   Sends your logs to files, sockets, i...
mtdowling/jmespath.php             2.6.1   Declaratively specify how to extract...
myclabs/deep-copy                  1.11.0  Create deep copies (clones) of your ...
nesbot/carbon                      2.58.0  An API extension for DateTime that s...
phar-io/manifest                   2.0.3   Component for reading phar.io manife...
phar-io/version                    3.2.1   Library for handling version informa...
php-http/client-common             2.5.0   Common HTTP Client implementations a...
php-http/discovery                 1.14.2  Finds installed HTTPlug implementati...
php-http/httplug                   2.3.0   HTTPlug, the HTTP client abstraction...
php-http/message                   1.13.0  HTTP Message related tools
php-http/message-factory           v1.0.2  Factory interfaces for PSR-7 HTTP Me...
php-http/multipart-stream-builder  1.2.0   A builder class that help you create...
php-http/promise                   1.1.0   Promise used for asynchronous HTTP r...
phpdocumentor/reflection-common    2.2.0   Common reflection classes used by ph...
phpdocumentor/reflection-docblock  5.3.0   With this component, a library can p...
phpdocumentor/type-resolver        1.6.1   A PSR-5 based resolver of Class name...
phpspec/prophecy                   v1.15.0 Highly opinionated mocking framework...
phpunit/php-code-coverage          7.0.15  Library that provides collection, pr...
phpunit/php-file-iterator          2.0.5   FilterIterator implementation that f...
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  2.1.3   Utility class for timing
phpunit/php-token-stream           4.0.4   Wrapper around PHP's tokenizer exten...
phpunit/phpunit                    8.5.26  The PHP Unit Testing framework.
psr/cache                          3.0.0   Common interface for caching libraries
psr/container                      2.0.2   Common Container Interface (PHP FIG ...
psr/http-client                    1.0.1   Common interface for HTTP clients
psr/http-factory                   1.0.1   Common interfaces for PSR-7 HTTP mes...
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.1.4   Common interface for logging libraries
psr/simple-cache                   1.0.1   Common interfaces for simple caching
ralouphie/getallheaders            3.0.3   A polyfill for getallheaders.
riverline/multipart-parser         2.0.9   One class library to parse multipart...
rize/uri-template                  0.3.4   PHP URI Template (RFC 6570) supports...
sebastian/code-unit-reverse-lookup 1.0.2   Looks up which function or method a ...
sebastian/comparator               3.0.3   Provides the functionality to compar...
sebastian/diff                     3.0.3   Diff implementation
sebastian/environment              4.2.4   Provides functionality to handle HHV...
sebastian/exporter                 3.1.4   Provides the functionality to export...
sebastian/global-state             3.0.2   Snapshotting of global state
sebastian/object-enumerator        3.0.4   Traverses array structures and objec...
sebastian/object-reflector         1.1.2   Allows reflection of object attribut...
sebastian/recursion-context        3.0.1   Provides functionality to recursivel...
sebastian/resource-operations      2.0.2   Provides a list of PHP built-in func...
sebastian/type                     1.1.4   Collection of value objects that rep...
sebastian/version                  2.0.1   Library that helps with managing the...
stella-maris/clock                 0.1.4   A pre-release of the proposed PSR-20...
symfony/browser-kit                v6.1.0  Simulates the behavior of a web brow...
symfony/console                    v6.1.0  Eases the creation of beautiful and ...
symfony/css-selector               v6.1.0  Converts CSS selectors to XPath expr...
symfony/deprecation-contracts      v3.1.0  A generic function and convention to...
symfony/dom-crawler                v6.1.0  Eases DOM navigation for HTML and XM...
symfony/http-client                v6.1.0  Provides powerful methods to fetch H...
symfony/http-client-contracts      v3.1.0  Generic abstractions related to HTTP...
symfony/mime                       v6.1.0  Allows manipulating MIME messages
symfony/options-resolver           v6.1.0  Provides an improved replacement for...
symfony/polyfill-ctype             v1.25.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.25.0 Symfony polyfill for intl's grapheme...
symfony/polyfill-intl-idn          v1.25.0 Symfony polyfill for intl's idn_to_a...
symfony/polyfill-intl-normalizer   v1.25.0 Symfony polyfill for intl's Normaliz...
symfony/polyfill-mbstring          v1.25.0 Symfony polyfill for the Mbstring ex...
symfony/polyfill-php72             v1.25.0 Symfony polyfill backporting some PH...
symfony/polyfill-php80             v1.25.0 Symfony polyfill backporting some PH...
symfony/polyfill-php81             v1.25.0 Symfony polyfill backporting some PH...
symfony/service-contracts          v3.1.0  Generic abstractions related to writ...
symfony/string                     v6.1.0  Provides an object-oriented API to s...
symfony/translation                v6.1.0  Provides tools to internationalize y...
symfony/translation-contracts      v3.1.0  Generic abstractions related to tran...
tecnickcom/tc-lib-barcode          1.17.11 PHP library to generate linear and b...
tecnickcom/tc-lib-color            1.14.10 PHP library to manipulate various co...
tecnickcom/tc-lib-file             1.7.11  PHP library to read byte-level data ...
tecnickcom/tc-lib-pdf              8.0.6   PHP PDF Library
tecnickcom/tc-lib-pdf-encrypt      1.6.7   PHP library to encrypt data for PDF
tecnickcom/tc-lib-pdf-font         1.9.6   PHP library containing PDF page form...
tecnickcom/tc-lib-pdf-graph        1.5.6   PHP library containing PDF graphic a...
tecnickcom/tc-lib-pdf-image        1.3.7   PHP library containing PDF Image met...
tecnickcom/tc-lib-pdf-page         2.5.6   PHP library containing PDF page form...
tecnickcom/tc-lib-unicode          1.4.7   PHP library containing Unicode methods
tecnickcom/tc-lib-unicode-data     1.7.6   PHP library containing Unicode defin...
theseer/tokenizer                  1.2.1   A small library for converting token...
voku/portable-ascii                2.0.1   Portable ASCII library - performance...
webmozart/assert                   1.10.0  Assertions to validate method input/...

```

### PHP version and extensions

```
PHP 7.4

composer                   2.3.5     Composer package
composer-plugin-api        2.3.0     The Composer Plugin API
composer-runtime-api       2.2.2     The Composer Runtime API
ext-apc                    5.1.21    The apc PHP extension
ext-apcu                   5.1.21    The apcu PHP extension
ext-bcmath                 7.4.29    The bcmath PHP extension
ext-calendar               7.4.29    The calendar PHP extension
ext-ctype                  7.4.29    The ctype PHP extension
ext-curl                   7.4.29    The curl PHP extension
ext-date                   7.4.29    The date PHP extension
ext-dom                    20031129  The dom PHP extension
ext-exif                   7.4.29    The exif PHP extension
ext-ffi                    7.4.29    The FFI PHP extension
ext-fileinfo               7.4.29    The fileinfo PHP extension
ext-filter                 7.4.29    The filter PHP extension
ext-ftp                    7.4.29    The ftp PHP extension
ext-gd                     7.4.29    The gd PHP extension
ext-gettext                7.4.29    The gettext PHP extension
ext-hash                   7.4.29    The hash PHP extension
ext-iconv                  7.4.29    The iconv PHP extension
ext-igbinary               3.2.7     The igbinary PHP extension
ext-imagick                3.7.0     The imagick PHP extension
ext-imap                   7.4.29    The imap PHP extension
ext-intl                   7.4.29    The intl PHP extension
ext-json                   7.4.29    The json PHP extension
ext-libxml                 7.4.29    The libxml PHP extension
ext-mbstring               7.4.29    The mbstring PHP extension
ext-memcache               4.0.5.2   The memcache PHP extension
ext-memcached              3.2.0     The memcached PHP extension
ext-mongodb                1.13.0    The mongodb PHP extension
ext-msgpack                2.1.2     The msgpack PHP extension
ext-mysqli                 7.4.29    The mysqli PHP extension
ext-mysqlnd                0         The mysqlnd PHP extension (actual version:...
ext-openssl                7.4.29    The openssl PHP extension
ext-pcntl                  7.4.29    The pcntl PHP extension
ext-pcre                   7.4.29    The pcre PHP extension
ext-pdo                    7.4.29    The PDO PHP extension
ext-pdo_mysql              7.4.29    The pdo_mysql PHP extension
ext-phar                   7.4.29    The Phar PHP extension
ext-posix                  7.4.29    The posix PHP extension
ext-readline               7.4.29    The readline PHP extension
ext-redis                  5.3.7     The redis PHP extension
ext-reflection             7.4.29    The Reflection PHP extension
ext-session                7.4.29    The session PHP extension
ext-shmop                  7.4.29    The shmop PHP extension
ext-simplexml              7.4.29    The SimpleXML PHP extension
ext-sockets                7.4.29    The sockets PHP extension
ext-sodium                 7.4.29    The sodium PHP extension
ext-spl                    7.4.29    The SPL PHP extension
ext-sysvmsg                7.4.29    The sysvmsg PHP extension
ext-sysvsem                7.4.29    The sysvsem PHP extension
ext-sysvshm                7.4.29    The sysvshm PHP extension
ext-tokenizer              7.4.29    The tokenizer PHP extension
ext-xml                    7.4.29    The xml PHP extension
ext-xmlreader              7.4.29    The xmlreader PHP extension
ext-xmlrpc                 7.4.29    The xmlrpc PHP extension
ext-xmlwriter              7.4.29    The xmlwriter PHP extension
ext-xsl                    7.4.29    The xsl PHP extension
ext-zend-opcache           7.4.29    The Zend OPcache PHP extension
ext-zip                    1.15.6    The zip PHP extension
ext-zlib                   7.4.29    The zlib PHP extension
lib-curl                   7.81.0    The curl library
lib-curl-libssh            0.9.6     curl libssh version
lib-curl-openssl           3.0.2.0   curl OpenSSL version (3.0.2.0)
lib-curl-zlib              1.2.11    curl zlib version
lib-date-timelib           2018.04   date timelib version
lib-date-zoneinfo          0         zoneinfo ("Olson") database for date
lib-fileinfo-libmagic      537       fileinfo libmagic version
lib-gd                     2.3.0     The gd library
lib-iconv                  2.35      The iconv library
lib-icu                    70.1      The ICU unicode and globalization support ...
lib-icu-cldr               40        ICU CLDR project version
lib-icu-unicode            14.0.0    ICU unicode version
lib-icu-zoneinfo           2022.1    zoneinfo ("Olson") database for icu
lib-imagick-imagemagick    6.9.11.60 The imagick-imagemagick library
lib-libsodium              1.0.18    The libsodium library
lib-libxml                 2.9.13    libxml library version
lib-libxslt                1.1.34    The libxslt library
lib-libxslt-libxml         2.9.13    libxml version libxslt is compiled against
lib-mbstring-libmbfl       1.3.2     mbstring libmbfl version
lib-mbstring-oniguruma     6.9.7     mbstring oniguruma version
lib-memcached-libmemcached 1.0.18    libmemcached version
lib-mongodb-libbson        1.21.1    libbson version of mongodb
lib-mongodb-libmongoc      1.21.1    libmongoc version of mongodb
lib-openssl                3.0.2.0   OpenSSL 3.0.2 15 Mar 2022
lib-pcre                   10.39     The pcre library
lib-pcre-unicode           14.0.0    PCRE Unicode version support
lib-zip-libzip             1.7.3     The zip-libzip library
lib-zlib                   1.2.11    The zlib library
php                        7.4.29    The PHP interpreter
php-64bit                  7.4.29    The PHP interpreter, 64bit
php-ipv6                   7.4.29    The PHP interpreter, with IPv6 support

```

### On which operating system(s) does the issue occur?

- [X] Linux
- [ ] MacOS
- [ ] Windows

### Steps to reproduce the issue.

```
$email = $user["email"];

        $phoneNumber = $user["phoneNumber"];

        $password = $user["password"];

        $firstname = $user["firstname"];

        $lastname = $user["lastname"];

        $photoUrl = $user["photoUrl"];

        if(!$photoUrl) {

            $photoUrl = "https://ui-avatars.com/api/?name={$firstname}+{$lastname}&size=128&background=CCCCCC&color=999999";

        }

        $request = \Kreait\Firebase\Request\CreateUser::new()
            ->withUnverifiedEmail($email)
            ->withPhoneNumber($phoneNumber)
            ->withClearTextPassword($password)
            ->withDisplayName("$firstname $lastname")
            ->withPhotoUrl($photoUrl);

        $payload = $this->auth->createUser($request); 
```

### Error message/Stack trace

```
CRITICAL - 2022-05-31 11:23:10 --> Client error: `POST https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser` resulted in a **`400 Bad Request`** response:
 (truncated...)

#0 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/kreait/firebase-php/src/Firebase/Auth/ApiClient.php(227): GuzzleHttp\Client->request()
#11 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/kreait/firebase-php/src/Firebase/Auth/ApiClient.php(46): Kreait\Firebase\Auth\ApiClient->requestApi()
#12 /var/www/sites/proppy.digital/api/app/ThirdParty/vendor/kreait/firebase-php/src/Firebase/Auth.php(143): Kreait\Firebase\Auth\ApiClient->createUser()
#13 /var/www/sites/proppy.digital/api/app/Libraries/Firebaseauth.php(27): Kreait\Firebase\Auth->createUser()
#14 /var/www/sites/proppy.digital/api/app/Controllers/User.php(129): App\Libraries\Firebaseauth->createUser()
#15 /var/www/sites/proppy.digital/api/vendor/codeigniter4/framework/system/CodeIgniter.php(832): App\Controllers\User->create_user()
#16 /var/www/sites/proppy.digital/api/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController()
#17 /var/www/sites/proppy.digital/api/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest()
#18 /var/www/sites/proppy.digital/api/public/index.php(45): CodeIgniter\CodeIgniter->run()
#19 {main}
```

**Comment by jeromegamez** [comment]
Unfortunately, I can't confirm the issue - I [just ran the integration test suite for the 5.x branch](https://github.com/kreait/firebase-php/runs/6674857183) (which creates and deletes many users) and there doesn't seem to be a problem.

You could try upgrading to the latest 6.x version to see if the problem remains, but it seems more likely that something in the input triggers the error. You could try wrapping the request in a try/catch block and inspect the exception

```php
try {
    $user = $auth->createUser(/* ... */);
} catch (Throwable $e) {
    echo $e->getMessage(); exit;
}

**Comment by the-code-writer** [comment]
Hi @jeromegamez . The issue has been resolved  by updating to the latest 6.x. Thank you very much.
