### ISSUE TITLE
Firebase Auth createCustomToken not working correctly on GCP  

### ISSUE THREAD

**Issue by universe-42** [kreait/firebase-php#743]
### Describe the bug

Hi,

When I creating [Custom Token](https://firebase-php.readthedocs.io/en/6.x/authentication.html#id2) on [GCP](https://cloud.google.com/) (Kubernetes with Identity workload) its returning token which Firebase Authentication then says: `INVALID_CUSTOM_TOKEN` with code 400.

Locally works fine, so i tried to debug this issue and there is what I found:
- Locally I am using service account json file with private key etc (so `CustomTokenGenerator` is used) and works
- on GCP there is no key file so Metadata server is used (so `CustomTokenViaGoogleIam` is used)

I think that issue come when `Configuration::forUnsecuredSigner()` is used in constructor in `CustomTokenViaGoogleIam`, because its not defining any Algorithm ID, but there [should be](https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library) `RS256`

I hope it can help

### Installed packages

```json
{
  "name": "...",
  "description": "...",
  "type": "project",
  "license": [
    "proprietary"
  ],
  "require": {
    "php": ">=7.4.0",
    "composer-plugin-api": "*",
    "kreait/firebase-php": "~5.26.3"
  }
}
```

### PHP version and extensions

```shell
composer               2.3.10   Composer package
composer-plugin-api    2.3.0    The Composer Plugin API
composer-runtime-api   2.2.2    The Composer Runtime API
ext-bcmath             7.4.30   The bcmath PHP extension
ext-ctype              7.4.30   The ctype PHP extension
ext-curl               7.4.30   The curl PHP extension
ext-date               7.4.30   The date PHP extension
ext-dom                20031129 The dom PHP extension
ext-fileinfo           7.4.30   The fileinfo PHP extension
ext-filter             7.4.30   The filter PHP extension
ext-ftp                7.4.30   The ftp PHP extension
ext-gd                 7.4.30   The gd PHP extension
ext-gmp                7.4.30   The gmp PHP extension
ext-grpc               1.48.0   The grpc PHP extension
ext-hash               7.4.30   The hash PHP extension
ext-iconv              7.4.30   The iconv PHP extension
ext-intl               7.4.30   The intl PHP extension
ext-json               7.4.30   The json PHP extension
ext-libxml             7.4.30   The libxml PHP extension
ext-mbstring           7.4.30   The mbstring PHP extension
ext-mysqli             7.4.30   The mysqli PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 7.4.30)
ext-openssl            7.4.30   The openssl PHP extension
ext-pcntl              7.4.30   The pcntl PHP extension
ext-pcre               7.4.30   The pcre PHP extension
ext-pdo                7.4.30   The PDO PHP extension
ext-pdo_mysql          7.4.30   The pdo_mysql PHP extension
ext-pdo_sqlite         7.4.30   The pdo_sqlite PHP extension
ext-phar               7.4.30   The Phar PHP extension
ext-posix              7.4.30   The posix PHP extension
ext-protobuf           3.21.3   The protobuf PHP extension
ext-readline           7.4.30   The readline PHP extension
ext-redis              5.3.7    The redis PHP extension
ext-reflection         7.4.30   The Reflection PHP extension
ext-session            7.4.30   The session PHP extension
ext-simplexml          7.4.30   The SimpleXML PHP extension
ext-sockets            7.4.30   The sockets PHP extension
ext-sodium             7.4.30   The sodium PHP extension
ext-spl                7.4.30   The SPL PHP extension
ext-sqlite3            7.4.30   The sqlite3 PHP extension
ext-tokenizer          7.4.30   The tokenizer PHP extension
ext-xdebug             3.1.5    The xdebug PHP extension
ext-xml                7.4.30   The xml PHP extension
ext-xmlreader          7.4.30   The xmlreader PHP extension
ext-xmlwriter          7.4.30   The xmlwriter PHP extension
ext-xsl                7.4.30   The xsl PHP extension
ext-zend-opcache       7.4.30   The Zend OPcache PHP extension
ext-zip                1.15.6   The zip PHP extension
ext-zlib               7.4.30   The zlib PHP extension
lib-curl               7.80.0   The curl library
lib-curl-openssl       1.1.1.17 curl OpenSSL version (1.1.1.17)
lib-curl-zlib          1.2.12   curl zlib version
lib-date-timelib       2018.04  date timelib version
lib-date-zoneinfo      2022.1   zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  537      fileinfo libmagic version
lib-gd                 2.0.35   The gd library
lib-gd-freetype        2.11.1   freetype version for gd
lib-gd-libjpeg         8.0      libjpeg version for gd
lib-gd-libpng          1.6.37   libpng version for gd
lib-gmp                6.2.1    The gmp library
lib-iconv              1.16     The iconv library
lib-icu                69.1     The ICU unicode and globalization support library
lib-icu-cldr           39       ICU CLDR project version
lib-icu-unicode        13.0.0   ICU unicode version
lib-icu-zoneinfo       2021.1   zoneinfo ("Olson") database for icu
lib-libsodium          1.0.18   The libsodium library
lib-libxml             2.9.14   libxml library version
lib-libxslt            1.1.35   The libxslt library
lib-libxslt-libxml     2.9.13   libxml version libxslt is compiled against
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.9.7    mbstring oniguruma version
lib-openssl            1.1.1.17 OpenSSL 1.1.1q  5 Jul 2022
lib-pcre               10.35    The pcre library
lib-pcre-unicode       13.0.0   PCRE Unicode version support
lib-pdo_sqlite-sqlite  3.36.0   The pdo_sqlite-sqlite library
lib-sqlite3-sqlite     3.36.0   The sqlite3-sqlite library
lib-zip-libzip         1.8.0    The zip-libzip library
lib-zlib               1.2.12   The zlib library
php                    7.4.30   The PHP interpreter
php-64bit              7.4.30   The PHP interpreter, 64bit
php-ipv6               7.4.30   The PHP interpreter, with IPv6 support
```

### Steps to reproduce the issue.

```php
$auth = (new Factory())->createAuth();
$customToken = $auth->createCustomToken($uid); // on GCP return JWT without 'alg'
```

### Error message/Stack trace

```shell
import { initializeApp } from "firebase/app";
import { getAuth, signInWithCustomToken } from "firebase/auth";

const app = initializeApp(environment.firebaseConfig);
const auth = getAuth(app);

function signIn(data: { token: string; }) {
	const token = data.token;
	return signInWithCustomToken(auth, token); // says error bellow
}


{
  "error": {
    "code": 400,
    "message": "INVALID_CUSTOM_TOKEN",
    "errors": [
      {
        "message": "INVALID_CUSTOM_TOKEN",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

**Comment by jeromegamez** [comment]
Hey there 👋,

unfortunately, older versions of the SDK no longer receive free support except for security fixes, unless you become a [GitHub Sponsor in one of the Firebase tiers](https://github.com/sponsors/jeromegamez), or a Firebase Sponsor backs this issue. I hope you understand 🙏 .

If the problem remains [after upgrading to the latest 6.x version of the SDK](https://github.com/kreait/firebase-php/blob/6.x/CHANGELOG.md#600---2022-01-07), please let me know and I'll look into it!

Thank you!

**Comment by jeromegamez** [comment]
I can confirm the problem with the latest 6.x release and will look into it as soon as my time allows 🤞

**Comment by opeadeyomoye** [comment]
Meantime, if your app's running on Compute Engine / Cloud Run / similar (not 100% sure about GKE) with credential autodiscovery, this might work:

```php
use Firebase\JWT\JWT; // package: firebase/php-jwt
use Google\Auth\Credentials\GCECredentials; // package: google/auth

// ...

protected function tryMakingCustomToken(string $uid)
{
    $creds = new GCECredentials();

    $nowInSeconds = time();

    $header = ['typ' => 'JWT', 'alg' => 'RS256'];
    $payload = [
        'iss' => $creds->getClientName(),
        'sub' => $creds->getClientName(),
        'aud' => 'https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit',
        'iat' => $nowInSeconds,
        'exp' => $nowInSeconds + (60 * 60),  // Maximum expiration time is one hour
        'uid' => $uid,
    ];

    $base64UrlHeader = JWT::urlsafeB64Encode(json_encode($header));
    $base64UrlPayload = JWT::urlsafeB64Encode(json_encode($payload));

    $signature = $creds->signBlob($base64UrlHeader . '.' . $base64UrlPayload);

    return sprintf('%s.%s.%s', $base64UrlHeader, $base64UrlPayload, $signature);
}
```

**Comment by jeromegamez** [comment]
@opeadeyomoye Thank you for sharing! Going through the credentials of the Auth Package is a good idea, I'll look into that.

**Comment by jeromegamez** [comment]
@opeadeyomoye @universe-42 Could you please test if #745 fixes the problem for you? 🙏

**Comment by jeromegamez** [comment]
@opeadeyomoye @universe-42 Please wait before testing, I think I missed something.

**Comment by jeromegamez** [comment]
@opeadeyomoye @universe-42 Now the PR is ready to be tested 💪🏻. Unfortunately, I'm not able to test this on GCE, but if you say that it works for you, I will merge and release it 🤞🏻

**Comment by universe-42** [comment]
Hi @jeromegamez. I did test on GKE (GCP Kubernetes) and getting this error:
```
Fatal error: Uncaught Kreait\Firebase\Exception\InvalidArgumentException: 
The given token could not be parsed: Error while decoding from Base64Url, invalid base64 characters detected 
in /srv/app/vendor/kreait/firebase-php/src/Firebase/Auth.php:392

Stack trace: 
#0 /srv/app/vendor/kreait/firebase-php/src/Firebase/Auth.php(383): Kreait\Firebase\Auth->parseToken('eyJ0eXAiOiJKV1Q...') 
#1 /srv/app/www/test.php(10): Kreait\Firebase\Auth->createCustomToken('...') 
#2 {main} thrown in /srv/app/vendor/kreait/firebase-php/src/Firebase/Auth.php on line 392
```
code:
```php
$auth = (new Factory())->createAuth();
$customToken = $auth->createCustomToken('...');
var_dump($customToken);
```
Thanks for helping me. I will send you some money for :coffee: and :cake:

**Comment by jeromegamez** [comment]
@universe-42 I think I've got it now, could you please try again? 🙏🏻

**Comment by universe-42** [comment]
@jeromegamez works perfect :ok_hand: :tada: thanks a lot!

**Comment by jeromegamez** [comment]
@universe-42 Thank *you* for discovering the problem and for your generous donation! 🌺 

I'll merge the PR now and release it later today. Thanks again!

**Comment by jeromegamez** [comment]
Here it is: https://github.com/kreait/firebase-php/releases/tag/6.9.3 🚀 

Thanks again!
