### ISSUE TITLE
firebase-php does not seem to verify idTokens issued by the firebase auth emulator without signature

### ISSUE THREAD

**Issue by ThomasCooks** [kreait/firebase-php#778]
### Describe the bug

I try to test my firebase-php based authentication with phpunit. As described in the [Testing and Local Development firebase-php docs](https://firebase-php.readthedocs.io/en/stable/testing.html#using-the-firebase-emulator-suite) I set up a firebase emulator for that.

The emulator works. The test is able to create and delete users via firebase-php and it is also able to create custom tokens. From the custom tokens I can sign in the user using `Auth::signInWithCustomToken()`. However, the generated ID token cannot be verified by firebase-php. I thought it could, because the [Auth Emulator part of the docs](https://firebase-php.readthedocs.io/en/stable/testing.html#auth-emulator) say firebase-php would accept unsigned ID tokens.

After having debugged the whole thing I unfortunately found that `Lcobucci\JWT\Token\Parser` won't accept JWTs _without_ signature. I can see that `Kreait\Firebase\JWT\Action\VerifyIdToken\WithLcobucciJWT::handle()` skips the `SignedWith` validation when connected to an emulator, but the JWT parser tries to parse the JWT first and complains about the missing signature. So it will throw `Lcobucci\JWT\Token\InvalidTokenStructure` long before the validation of the signature is being skipped.

I checked the [emulator suit documentation](https://firebase.google.com/docs/emulator-suite/connect_auth#id_tokens) which stats the emulator will always issue unsigned ID tokens.

What can I do to come around this issue? With the limitation of unsigned tokens and the `lcobucci\jwt` package I don't see a way to test authentication with the firebase-emulator.

### Installed packages

```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.2",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "kreait/firebase-bundle": "^5.0",
        "symfony/console": "6.2.*",
        "symfony/dotenv": "6.2.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.2.*",
        "symfony/runtime": "6.2.*",
        "symfony/security-bundle": "6.2.*",
        "symfony/yaml": "6.2.*"
    },
    "config": {
        "allow-plugins": {
            "php-http/discovery": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.2.*"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^9.5",
        "symfony/browser-kit": "6.2.*",
        "symfony/css-selector": "6.2.*",
        "symfony/phpunit-bridge": "^6.2"
    }
}
```

### PHP version and extensions

```shell
# composer show --platform
composer               2.5.4    Composer package
composer-plugin-api    2.3.0    The Composer Plugin API
composer-runtime-api   2.2.2    The Composer Runtime API
ext-ctype              8.2.3    The ctype PHP extension
ext-curl               8.2.3    The curl PHP extension
ext-date               8.2.3    The date PHP extension
ext-dom                20031129 The dom PHP extension
ext-fileinfo           8.2.3    The fileinfo PHP extension
ext-filter             8.2.3    The filter PHP extension
ext-ftp                8.2.3    The ftp PHP extension
ext-hash               8.2.3    The hash PHP extension
ext-iconv              8.2.3    The iconv PHP extension
ext-json               8.2.3    The json PHP extension
ext-libxml             8.2.3    The libxml PHP extension
ext-mbstring           8.2.3    The mbstring PHP extension
ext-mysqlnd            0        The mysqlnd PHP extension (actual version: mysqlnd 8.2.3)
ext-openssl            8.2.3    The openssl PHP extension
ext-pcre               8.2.3    The pcre PHP extension
ext-pdo                8.2.3    The PDO PHP extension
ext-pdo_sqlite         8.2.3    The pdo_sqlite PHP extension
ext-phar               8.2.3    The Phar PHP extension
ext-posix              8.2.3    The posix PHP extension
ext-random             8.2.3    The random PHP extension
ext-readline           8.2.3    The readline PHP extension
ext-reflection         8.2.3    The Reflection PHP extension
ext-session            8.2.3    The session PHP extension
ext-simplexml          8.2.3    The SimpleXML PHP extension
ext-sodium             8.2.3    The sodium PHP extension
ext-spl                8.2.3    The SPL PHP extension
ext-sqlite3            8.2.3    The sqlite3 PHP extension
ext-tokenizer          8.2.3    The tokenizer PHP extension
ext-xdebug             3.2.0    The xdebug PHP extension
ext-xml                8.2.3    The xml PHP extension
ext-xmlreader          8.2.3    The xmlreader PHP extension
ext-xmlwriter          8.2.3    The xmlwriter PHP extension
ext-zend-opcache       8.2.3    The Zend OPcache PHP extension
ext-zip                1.21.1   The zip PHP extension
ext-zlib               8.2.3    The zlib PHP extension
lib-curl               7.74.0   The curl library
lib-curl-libssh2       1.9.0    curl libssh2 version
lib-curl-openssl       1.1.1.14 curl OpenSSL version (1.1.1.14)
lib-curl-zlib          1.2.11   curl zlib version
lib-date-timelib       2022.03  date timelib version
lib-date-zoneinfo      2022.7   zoneinfo ("Olson") database for date
lib-fileinfo-libmagic  540      fileinfo libmagic version
lib-iconv              2.31     The iconv library
lib-libsodium          1.0.18   The libsodium library
lib-libxml             2.9.10   libxml library version
lib-mbstring-libmbfl   1.3.2    mbstring libmbfl version
lib-mbstring-oniguruma 6.9.6    mbstring oniguruma version
lib-openssl            1.1.1.14 OpenSSL 1.1.1n  15 Mar 2022
lib-pcre               10.40    The pcre library
lib-pcre-unicode       14.0.0   PCRE Unicode version support
lib-pdo_sqlite-sqlite  3.34.1   The pdo_sqlite-sqlite library
lib-sqlite3-sqlite     3.34.1   The sqlite3-sqlite library
lib-zip-libzip         1.7.3    The zip-libzip library
lib-zlib               1.2.11   The zlib library
php                    8.2.3    The PHP interpreter
php-64bit              8.2.3    The PHP interpreter, 64bit
php-ipv6               8.2.3    The PHP interpreter, with IPv6 support
```

### Steps to reproduce the issue.

```php

// From a KernelTestCase in Symfony - feel free to replace this line with any factory call
$auth = $this->getContainer()->get(\Kreait\Firebase\Contract\Auth::class);

$testUser = $auth->createUserWithEmailAndPassword('testuser@myapp.com', 'password123');
$customToken = $auth->createCustomToken($testUser->uid);
$signInResult = $auth->signInWithCustomToken($customToken);

try {
    $auth->verifyIdToken($signInResult->idToken());
} catch (\Exception $e) {
    echo get_class($e) . PHP_EOL . PHP_EOL;
    echo $e->getMessage() . PHP_EOL;
    echo $e->getTraceAsString() . PHP_EOL;
}
```

### Error message/Stack trace

```shell
Kreait\Firebase\Exception\Auth\FailedToVerifyToken

The value 'eyJhbGciOiJub25...' is not a verified ID token:
- The token is invalid
- The JWT string is missing the Signature part

#0 /var/www/app/tests/IndexControllerTest.php(55): Kreait\Firebase\Auth->verifyIdToken('eyJhbGciOiJub25...')
#1 /var/www/app/vendor/phpunit/phpunit/src/Framework/TestCase.php(1207): App\Tests\IndexControllerTest->setUp()
#2 /var/www/app/vendor/phpunit/phpunit/src/Framework/TestResult.php(728): PHPUnit\Framework\TestCase->runBare()
#3 /var/www/app/vendor/phpunit/phpunit/src/Framework/TestCase.php(964): PHPUnit\Framework\TestResult->run(Object(App\Tests\IndexControllerTest))
#4 /var/www/app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 /var/www/app/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /var/www/app/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(653): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /var/www/app/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#8 /var/www/app/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#9 /var/www/app/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#10 {main}
```

**Comment by jeromegamez** [comment]
Unfortunately, this was an unintended breaking change when I added support for `lcobucci/jwt` 5, meaning: I didn't realize it was a breaking change. I'm currently working on bringing this back, but I can't give an ETA because, at the moment, I have very limited time.

In the meantime, if you don't rely on `lcobucci/jwt` yourself, you could change the dependency in your `composer.json` file to `"kreait/firebase-php": "~7.0.3"` - you won't lose features of the SDK, and I will not add new ones until support for the Auth Emulator is restored.

I'm sorry for the inconvenience!

**Comment by ThomasCooks** [comment]
Thank you for looking promptly into the issue. Downgrading `kreait/firebase-php` to `~7.0.3` and `lcobucci/jwt` to `^4.2.1` worked. My application is able to verify unsigned ID tokens now. Great!

I am going to continue to subscribe to this issue. I'll get notified whenever you are ready and there is some progress.

Thanks again!

**Comment by jeromegamez** [comment]
Hey @ThomasCooks - I just released https://github.com/kreait/firebase-php/releases/tag/7.2.0 and am running the tests against the auth emulator in the Emulator Tests workflow myself, so I'm confident this will also work for you 🤞🏻, but please let me know if it doesn't!

**Comment by ThomasCooks** [comment]
Hi @jeromegamez,

Thanks for providing a fix quickly. I just tested the new version and et voilà it works, great!

Dankeschön!
